swagger: "2.0"
info:
  title: "API do seu projeto"
  version: "1.0.0"
basePath: "/"
paths:
  /users:
    get:
      summary: Lista de usuários
      description: Retorna uma lista de usuários.
      responses:
        "200":
          description: OK
